name: GCP Deployment Pipeline

on:
  workflow_run:
    workflows: ["testing"]  # Nombre exacto del primer workflow
    types:
      - completed
    branches:
      - main

jobs:
  gcp_deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Solo si los tests pasaron
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Autenticarse con la cuenta de servicio
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Paso 3: Autenticar Docker en Artifact Registry
      - name: Configure Docker authentication
        run: |
          gcloud auth configure-docker europe-southwest1-docker.pkg.dev

      # Paso 4: Construir imagen Docker
      - name: Build Docker image
        run: |
          docker build \
            -t europe-southwest1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/coms-repository/coms-image:latest \
            .

      # Paso 5: Subir imagen a Artifact Registry
      - name: Push Docker image
        run: |
          docker push \
            europe-southwest1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/coms-repository/coms-image:latest

      # Paso 6: Desplegar en Google Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ secrets.CART_RUN_SERVICE }}
          image: europe-southwest1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/coms-repository/coms-image:latest
          region: ${{ secrets.GCP_REGION }}
          flags: --allow-unauthenticated